---
- name: Start cassandra or dse service
  shell: service dse restart
#  service:
#    name: "{{ srvc_name }}"
#    state: restarted
  become: true
  become_user: root

- name: Wait for Cassandra process is up and running
  wait_for:
    host: "{{ ansible_host }}"
    port: 9042
    delay: 1
    timeout: 300
